### ISSUE TITLE
Keep Dropdowns highlighted

### ISSUE THREAD

**Issue by bmccoy11** [braginteractive/materialwp#8]
I think the dropdown menus should stay highlighted when opened, and the dropdown should open on hover.

**Comment by braginteractive** [comment]
I am not sure what you mean by "stay highlighted", but you could probably apply some custom CSS to make this happen. 

As for the hover dropdown. I don't see this happening since there is not a hover on mobile devices. This would need to be a customization. Check this out: http://stackoverflow.com/questions/8878033/how-to-make-twitter-bootstrap-menu-dropdown-on-hover-rather-than-click

**Comment by bmccoy11** [comment]
By 'stay highlighted', I mean the dropdown behavior isn't the same as http://materialwp.com , the dropdown there stays highlighted (shaded) when clicked. It doesn't do that on my site, https://bmccoy.cf .

**Comment by braginteractive** [comment]
Seems https://github.com/FezVrasta/bootstrap-material-design made some changes to the script which made the highlight go away.

**Comment by bmccoy11** [comment]
Can you reverse those changes? It just doesn't look right. When another page is opened/highlighted, the dropdown doesn't highlight when opened.

**Comment by braginteractive** [comment]
The Material Bootstrap Theme must have taken out those styles. You can see the dropdown doesn't stay highlighted in his examples here: http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html

I plan to stay in sync with his commits so the theme doesn't have different css/js files. You can add custom styles to your theme/child to make overrides.
